# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25340a05fe7a44661a6ef3d9ae46601e7e43dcc5dfe703ebbd725eb3677454bb73f3b735edebe5b3e32db06aee51b64cb7382c7502280098d998d21433c5ee79
  gmaps_api_key: <%= ENV["GMAPS_API_KEY"] %>
  gmaps_static_api_key: <%= ENV["GMAPS_STATIC_API_KEY"] %>
  gmaps_geocoding_api_key: <%= ENV["GMAPS_GEOCODING_API_KEY"] %>

test:
  secret_key_base: aab722cf61f7b4a7df499c13d741ccdd3c905b33cc0dd24a8cc08ae8b073d310366b2f294443e242ef6ded444857bc9013a45922cdab0d307188444ba7ca905c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmaps_api_key: <%= ENV["GMAPS_API_KEY"] %>
  gmaps_static_api_key: <%= ENV["GMAPS_STATIC_API_KEY"] %>
  gmaps_geocoding_api_key: <%= ENV["GMAPS_GEOCODING_API_KEY"] %>


